<?php
declare(strict_types=1);

namespace TrayDigita\OAuth2\Grants;

use TrayDigita\OAuth2\Abstracts\AbstractGrant;
use TrayDigita\OAuth2\Enums\RequestType;
use TrayDigita\OAuth2\Exceptions\UnsatisfiedGrantParameterException;
use TrayDigita\OAuth2\Interfaces\Requests\Grants\AuthorizationCodeGrantInterface;

/**
 * ## The authorization code is obtained by using an authorization server
 * as an intermediary between the client and resource owner.
 *
 * Instead of requesting authorization directly from the resource owner, the client
 * directs the resource owner to an authorization server (via its
 * user-agent as defined in [RFC2616]), which in turn directs the
 * resource owner back to the client with the authorization code.
 *
 * Before directing the resource owner back to the client with the
 * authorization code, the authorization server authenticates the
 * resource owner and obtains authorization.  Because the resource owner
 * only authenticates with the authorization server, the resource
 * owner's credentials are never shared with the client.
 *
 * The authorization code provides a few important security benefits,
 * such as the ability to authenticate the client, as well as the
 * transmission of the access token directly to the client without
 * passing it through the resource owner's user-agent and potentially
 * exposing it to others, including the resource owner.
 *
 * ### Flow:
 * <code>
 * +----------+
 * | Resource |
 * |   Owner  |
 * |          |
 * +----------+
 * ^
 * |
 * (B)
 * +----|-----+          Client Identifier      +---------------+
 * |         -+----(A)-- & Redirection URI ---->|               |
 * |  User-   |                                 | Authorization |
 * |  Agent  -+----(B)-- User authenticates --->|     Server    |
 * |          |                                 |               |
 * |         -+----(C)-- Authorization Code ---<|               |
 * +-|----|---+                                 +---------------+
 *   |    |                                         ^      v
 *  (A)  (C)                                        |      |
 *   |    |                                         |      |
 *   ^    v                                         |      |
 * +---------+                                      |      |
 * |         |>---(D)-- Authorization Code ---------'      |
 * |  Client |          & Redirection URI                  |
 * |         |                                             |
 * |         |<---(E)----- Access Token -------------------'
 * +---------+       (w/ Optional Refresh Token)
 *
 * Note: The lines illustrating steps (A), (B), and (C) are broken into
 * two parts as they pass through the user-agent.
 *
 * Authorization Code Flow
 * </code>
 *
 * ### Example Request:
 * <code>
 * GET /authorize?response_type=code&client_id=s6BhdRkqt3&state=xyz
 * &redirect_uri=https%3A%2F%2Fclient%2Eexample%2Ecom%2Fcb HTTP/1.1
 * Host: server.example.com
 * </code>
 *
 * ### Example Response:
 * <code>
 * HTTP/1.1 302 Found
 * Location: https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz
 * </code>
 *
 * @note The authorization code is bound to the client identifier and redirection URI.
 * If the redirection URI is included in the authorization request,
 * the authorization code is bound to the redirection URI as well.
 * If the redirection URI is omitted from the authorization request.
 *
 * ### Authorization Response
 * <ol>
 *      <li>
 *          <code>code</code> REQUIRED.
 * The authorization code generated by the
 * authorization server.  The authorization code MUST expire
 * shortly after it is issued to mitigate the risk of leaks.  A
 * maximum authorization code lifetime of 10 minutes is
 * RECOMMENDED.  The client MUST NOT use the authorization code
 * more than once.  If an authorization code is used more than
 * once, the authorization server MUST deny the request and SHOULD
 * revoke (when possible) all tokens previously issued based on
 * that authorization code.  The authorization code is bound to
 * the client identifier and redirection URI.
 *      </li>
 *      <li>
 *          <code>state</code> REQUIRED if the "state" parameter was present in the client
 * authorization request. The exact value received from the
 * client.
 *      </li>
 * </ol>
 * @link https://datatracker.ietf.org/doc/html/rfc6749#section-1.3.1 Intoduction about athorization code
 * @link https://datatracker.ietf.org/doc/html/rfc6749#section-4.1 Authorization Code Grant (RFC 6749, §4.1)
 * @link https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2 Authorization Response
 * @see https://datatracker.ietf.org/doc/html/rfc2616 RFC2616 - HTTP
 *
 * @template-extends AbstractGrant<"authorization_code">
 */
class AuthorizationCodeGrant extends AbstractGrant implements AuthorizationCodeGrantInterface
{
    /**
     * @inheritdoc
     * @return "authorization_code"
     */
    public function getGrantType(): string
    {
        return self::TYPE;
    }

    /**
     * Assert that the required parameters are present in the given parameters array.
     *
     * @param array<string, mixed> $parameters The parameters to check.
     * @throws UnsatisfiedGrantParameterException if any required parameter is missing.
     */
    protected function assertRequiredParameters(RequestType $requestType, array $parameters): void
    {
        parent::assertRequiredParameters($requestType, $parameters);
        if (!isset($parameters['code'])
            || !is_string($parameters['code'])
            || trim($parameters['code']) === ''
        ) {
            throw new UnsatisfiedGrantParameterException(
                'The "code" parameter is required and must be a non-empty string.'
            );
        }
        if (isset($parameters['redirect_uri'])
            && !is_string($parameters['redirect_uri'])
        ) {
            throw new UnsatisfiedGrantParameterException(
                'The "redirect_uri" parameter must be a string if provided.'
            );
        }
        if (isset($parameters['client_id'])
            && !is_string($parameters['client_id'])
        ) {
            throw new UnsatisfiedGrantParameterException(
                'The "client_id" parameter must be a string if provided.'
            );
        }
        if ($requestType === RequestType::TOKEN
            && !isset($parameters['client_id'])
        ) {
            throw new UnsatisfiedGrantParameterException(
                'The "client_id" parameter is required for token requests if client authentication is not provided.'
            );
        }
    }

    /**
     * @inheritdoc
     * @return list<non-empty-string>&list<'redirect_uri','client_id','scope','state'>
     */
    public function getOptionalParameters(RequestType $requestType): array
    {
        return [
            // REQUIRED, if the "redirect_uri" parameter was included in the
            //         authorization request as described in Section 4.1.1, and their
            //         values MUST be identical.
            // https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1
            'redirect_uri',
            // REQUIRED, if the client is not authenticating with the
            //         authorization server as described in Section 3.2.1.
            // https://datatracker.ietf.org/doc/html/rfc6749#section-3.2.1
            'client_id',
            'scope',
            'state'
        ];
    }

    /**
     * @inheritdoc
     * The client MUST include the "grant_type" parameter and set it to "authorization_code".
     * The client MUST also include the "code" parameter,
     * which contains the authorization code received from the authorization server.
     * If the "redirect_uri" parameter was included in the authorization request,
     * the client MUST include the "redirect_uri" parameter with the same value as the authorization
     *
     * @return list<non-empty-string>&list<'grant_type','code', 'client_id'|string>
     */
    public function getRequiredParameters(RequestType $requestType): array
    {
        $grants = [
            'grant_type',
            'code'
        ];
        if ($requestType === RequestType::TOKEN) {
            $grants[] = 'client_id';
        }
        return $grants;
    }
}
