<?php
declare(strict_types=1);

namespace TrayDigita\OAuth2\Interfaces\Requests\Grants;

use TrayDigita\OAuth2\Enums\RequestType;

/**
 * ## The authorization code is obtained by using an authorization server
 * as an intermediary between the client and resource owner.
 *
 * Instead of requesting authorization directly from the resource owner, the client
 * directs the resource owner to an authorization server (via its
 * user-agent as defined in [RFC2616]), which in turn directs the
 * resource owner back to the client with the authorization code.
 *
 * Before directing the resource owner back to the client with the
 * authorization code, the authorization server authenticates the
 * resource owner and obtains authorization.  Because the resource owner
 * only authenticates with the authorization server, the resource
 * owner's credentials are never shared with the client.
 *
 * The authorization code provides a few important security benefits,
 * such as the ability to authenticate the client, as well as the
 * transmission of the access token directly to the client without
 * passing it through the resource owner's user-agent and potentially
 * exposing it to others, including the resource owner.
 *
 * ### Flow:
 * <code>
 * +----------+
 * | Resource |
 * |   Owner  |
 * |          |
 * +----------+
 * ^
 * |
 * (B)
 * +----|-----+          Client Identifier      +---------------+
 * |         -+----(A)-- & Redirection URI ---->|               |
 * |  User-   |                                 | Authorization |
 * |  Agent  -+----(B)-- User authenticates --->|     Server    |
 * |          |                                 |               |
 * |         -+----(C)-- Authorization Code ---<|               |
 * +-|----|---+                                 +---------------+
 *   |    |                                         ^      v
 *  (A)  (C)                                        |      |
 *   |    |                                         |      |
 *   ^    v                                         |      |
 * +---------+                                      |      |
 * |         |>---(D)-- Authorization Code ---------'      |
 * |  Client |          & Redirection URI                  |
 * |         |                                             |
 * |         |<---(E)----- Access Token -------------------'
 * +---------+       (w/ Optional Refresh Token)
 *
 * Note: The lines illustrating steps (A), (B), and (C) are broken into
 * two parts as they pass through the user-agent.
 *
 * Authorization Code Flow
 * </code>
 *
 * ### Example Request:
 * <code>
 * GET /authorize?response_type=code&client_id=s6BhdRkqt3&state=xyz
 * &redirect_uri=https%3A%2F%2Fclient%2Eexample%2Ecom%2Fcb HTTP/1.1
 * Host: server.example.com
 * </code>
 *
 * ### Example Response:
 * <code>
 * HTTP/1.1 302 Found
 * Location: https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz
 * </code>
 *
 * @note The authorization code is bound to the client identifier and redirection URI.
 * If the redirection URI is included in the authorization request,
 * the authorization code is bound to the redirection URI as well.
 * If the redirection URI is omitted from the authorization request.
 *
 * ### Authorization Response
 * <ol>
 *      <li>
 *          <code>code</code> REQUIRED.
 * The authorization code generated by the
 * authorization server.  The authorization code MUST expire
 * shortly after it is issued to mitigate the risk of leaks.  A
 * maximum authorization code lifetime of 10 minutes is
 * RECOMMENDED.  The client MUST NOT use the authorization code
 * more than once.  If an authorization code is used more than
 * once, the authorization server MUST deny the request and SHOULD
 * revoke (when possible) all tokens previously issued based on
 * that authorization code.  The authorization code is bound to
 * the client identifier and redirection URI.
 *      </li>
 *      <li>
 *          <code>state</code> REQUIRED if the "state" parameter was present in the client
 * authorization request. The exact value received from the
 * client.
 *      </li>
 * </ol>
 * @link https://datatracker.ietf.org/doc/html/rfc6749#section-1.3.1 Intoduction about athorization code
 * @link https://datatracker.ietf.org/doc/html/rfc6749#section-4.1 Authorization Code Grant (RFC 6749, §4.1)
 * @link https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2 Authorization Response
 * @see https://datatracker.ietf.org/doc/html/rfc2616 RFC2616 - HTTP
 *
 * @template-extends GrantTypeAuthorizationInterface<"authorization_code", "response_type", "code">
 * @template-extends GrantTypeTokenInterface<"authorization_code", "response_type", "code">
 */
interface AuthorizationCodeGrantInterface extends
    GrantTypeAuthorizationInterface,
    GrantTypeTokenInterface
{
    /**
     * Grant name constant
     * @var "authorization_code"
     */
    public const TYPE = 'authorization_code';

    /**
     * @inheritdoc
     * @return "response_type"
     */
    public function getGrantTypeKey(): string;

    /**
     * check if grant type valid
     *
     * @param string $grantTypeRequest
     * @return bool
     * @phpstan-return ($grantTypeRequest is "code" ? true : false)
     */
    public function isGrantTypeRequestValid(string $grantTypeRequest) : bool;

    /**
     * Required parameters for the grant type, including the "grant_type" parameter.
     * The "grant_type" parameter is required in the token request
     * and must be set to the value of the "grant_type" parameter as defined in
     * the authorization grant type being used.
     *
     * @param RequestType $requestType The type of the request (e.g., authorization request, token request, etc.)
     * @return list<non-empty-string>&list<'grant_type','client_id'>
     */
    public function getRequiredClientRequestParameters(RequestType $requestType): array;

    /**
     * @inheritdoc
     *
     * @template TKey of string
     * @template TValue
     * @param RequestType $requestType The type of the request (e.g., authorization request, token request, etc.)
     * @param array<TKey, TValue> $parameters
     * @param array<TKey, TValue> $defaultParameters
     * @return array{
     *     "grant_type" : 'authorization_code',
     *     "code" : non-empty-string,
     *     "redirect_uri"?: non-empty-string,
     *     "scope"?: non-empty-string,
     *     "state"?: non-empty-string,
     *     ...<TKey, TValue>
     * }
     */
    public function prepareClientRequestParameters(
        RequestType $requestType,
        array $parameters,
        array $defaultParameters
    ): array;
}
