<?php
declare(strict_types=1);

namespace TrayDigita\OAuth2\Interfaces\Parameters;

/**
 * The authorization code generated by the authorization server.
 * The client MUST NOT use the authorization code more than once.
 * If an authorization code is used more than once,
 * the authorization server MUST deny the request and SHOULD revoke (when possible)
 * all tokens previously issued based on that authorization code.
 * The authorization code MUST expire shortly after it is issued to mitigate the risk of leaks.
 * A maximum authorization code lifetime of 10 minutes is RECOMMENDED.
 * The client MUST NOT use the authorization code if it has expired.
 * If an expired authorization code is used,
 * the authorization server MUST deny the request and SHOULD revoke (when possible)
 * all tokens previously issued based on that authorization code.
 *
 * <code>
 *     Parameter usage location: authorization response, token response
 * </code>
 * The "code" element is defined in Section 4.1.3:
 * <code>
 *     code = 1*VSCHAR
 * </code>
 * @link https://datatracker.ietf.org/doc/html/rfc6749#section-11.2.2
 * @link https://datatracker.ietf.org/doc/html/rfc6749#appendix-A.11
 * @link https://datatracker.ietf.org/doc/html/rfc6749#section-1.3.1
 *
 * @meta code: non-empty-string
 */
interface CodeParameterInterface
{
    /**
     * The code parameter name as defined in RFC6749#section-4.1.3
     */
    public const CODE_PARAMETER_NAME = 'code';

    /**
     * The authorization code generated by the authorization server.
     *
     * @return non-empty-string
     */
    public function getCode() : string;
}
